### ISSUE TITLE
Estrutura mínima da documentação legível

### ISSUE THREAD

**Issue by nitaibezerra** [medialab-ufg/ontologia-gestao-cultural#1]
Abaixo segue uma estrutura mínima com tópicos essenciais:

1. Introdução
2. Participantes e processo de construção
3. Núcleo do modelo (diagrama)
4. [Referências Externas do Modelo]
5. Modelo Completo (diagrama)
6. Modelo Conceitual
6.1. Escopo
6.2. Não-escopo
6.3. Perguntas-requisito
6.4. Conceitos
6.4.1. ....
6.4.2. ....
6.5. Relacionamentos
6.6. Ligações com Conceitos Externos
7. Referências

Esta estrutura foi inspirada em vários exemplos internacionais e neste caso aqui http://vocab.e.gov.br/2011/09/org

**Comment by daltonmartins** [comment]
Implementado no documento.
